name: génération de blocklist.txt

on:
  schedule:
    - cron: '0 0,8,16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v6

      - name: Installer Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14.5'

      - name: configurer fuseau horaire Europe/Paris et locale fr_FR.UTF-8
        run: |
          sudo apt-get update
          sudo apt-get install -y locales tzdata
          sudo timedatectl set-timezone Europe/Paris
          sudo locale-gen fr_FR.UTF-8
          sudo update-locale LANG=fr_FR.UTF-8
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Définir LANG et LC_ALL pour l'environnement
        run: |
          echo "LANG=fr_FR.UTF-8" >> $GITHUB_ENV
          echo "LC_ALL=fr_FR.UTF-8" >> $GITHUB_ENV

      - name: Exécuter blocklist.py
        run: python blocklist.py
        env:
          LANG: fr_FR.UTF-8
          LC_ALL: fr_FR.UTF-8

      - name: commit et push de blocklist.txt et README.md
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add blocklist.txt README.md
          git commit -m "🤖 mise à jour automatique - $(date '+%d/%m/%Y %H:%M')" || echo "aucun changement à committer"
          git push
