name: Nettoyage des filtres AdGuard

on:
  workflow_dispatch:
    inputs:
      force_run:
        description: "Forcer l'exécution"
        required: true
        default: 'true'

jobs:
  clean_filters:
    runs-on: ubuntu-latest

    steps:
    - name: Vérifier le dépôt
      uses: actions/checkout@v3

    - name: Télécharger General.txt et blocklist.txt
      run: |
        curl -O https://raw.githubusercontent.com/mondepot/Blocklists/refs/heads/main/General.txt
        curl -O https://raw.githubusercontent.com/mondepot/Blocklists/refs/heads/main/blocklist.txt

    - name: Exécuter le script de nettoyage des filtres
      run: |
        python3 cleanup_filters.py

    - name: Vérifier le répertoire après nettoyage
      run: |
        ls -la  # Liste les fichiers du répertoire actuel pour vérifier si General_clean_*.txt existe

    - name: Déplacer et ajouter le fichier nettoyé au dépôt
      run: |
        # Vérifier si le fichier a bien été créé avant de tenter de le déplacer
        if ls General_clean_*.txt 1> /dev/null 2>&1; then
          mkdir -p cleaned_filters
          mv General_clean_*.txt ./cleaned_filters/
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./cleaned_filters/*
          git commit -m "Ajouter le fichier nettoyé des filtres"
          git push
        else
          echo "Le fichier General_clean_*.txt n'a pas été trouvé"
          exit 1
        fi
