name: Filter AdGuard Rules

on:
  schedule:
    - cron: '0 3 * * *' # Exécute tous les jours à 3h du matin
  workflow_dispatch: # Permet de lancer le workflow manuellement

jobs:
  filter-rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Assurez-vous de récupérer tout l'historique pour pouvoir pousser

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' # Spécifiez la version de Python que vous souhaitez utiliser

    - name: Download the filter file
      run: |
        curl -o filter.txt https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt

    - name: Run Python script to filter the file
      run: |
        python filter_rules.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add Cosmetic-AdGuardBase.txt
        git commit -m "Mise à jour automatique des règles filtrées"
        git push
