# .github/workflows/filter.yml
name: Filter Blocklist

on:
  schedule:
    - cron: '0 1 * * *'  # Tous les jours à 1h du matin UTC
  workflow_dispatch:

jobs:
  run-filter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install tldextract requests

      - name: Run filter script
        run: python light.py

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add light.txt
          git diff --cached --quiet || git commit -m "Update light.txt with new daily rules"
          git push
