name: Mise à jour des filtres AdGuard

on:
  schedule:
    - cron: '0 1,9,17 * * *'  # exécution à 01h, 09h, 17h UTC
  workflow_dispatch:

jobs:
  update-filters:
    runs-on: ubuntu-latest
    
    steps:
    - name: Vérification du code
      uses: actions/checkout@v2

    - name: Installer Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Exécuter le script Python
      run: |
        python local-adguardbase.py

    - name: Commit et push des changements
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add local-adguardbase.txt
        git diff --quiet || git commit -m "Mise à jour des filtres AdGuard"
        git push

