name: Génération de blocklist.txt

on:
  schedule:
    - cron: '0 */12 * * *'  # Tous les jours à 00:00 et 12:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer local france
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen fr_FR.UTF-8
          sudo update-locale LANG=fr_FR.UTF-8
          echo "LANG=fr_FR.UTF-8" >> $GITHUB_ENV
          echo "LC_ALL=fr_FR.UTF-8" >> $GITHUB_ENV

      - name: Exécuter test.py
        env:
          LANG: fr_FR.UTF-8
          LC_ALL: fr_FR.UTF-8
        run: python test.py

      - name: Commit et push de blocklist.txt
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add blocklist.txt
          git commit -m "🛡️ Mise à jour automatique [$(date '+%d/%m/%Y %H:%M')]" || echo "Rien à committer"
          git push
