name: Filtrage du fichier

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x' 

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install requests

      - name: Download and run Python script
        run: |
          # Télécharger le fichier à partir de l'URL et exécuter le script
          curl -O https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt
          echo '
import requests

def nettoyer_fichier(url, output_file):
    response = requests.get(url)
    if response.status_code != 200:
        return

    lignes_filtrées = []

    for ligne in response.text.splitlines():
        if ligne.startswith("!"):
            continue
        if ligne.startswith("||") and ligne.endswith("^"):
            continue
        lignes_filtrées.append(ligne)

    with open(output_file, "w") as f:
        for ligne in lignes_filtrées:
            f.write(f"{ligne}\\n")

url = "https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt"
output_file = "test.txt"
nettoyer_fichier(url, output_file)
          ' > test.py

          python3 test.py

      - name: Commit and push filtered file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add test.txt
          git commit -m "Ajout du fichier filtré"
          git push
