name: Filtrage du fichier

on:
  workflow_dispatch:

jobs:
  nettoyage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install requests

      - name: Download the filter file
        run: curl -O https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt

      - name: Download the Python script (test.py)
        run: curl -O https://example.com/path/to/test.py  # Remplace par l'URL correcte du fichier test.py

      - name: Run Python script
        run: python3 test.py

      - name: Commit and push filtered file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add test.txt
          git commit -m "Ajout du fichier filtré"
          git push
